version: '2'
services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  cryptpad:
    build:
      context: .
      args:
        - VERSION=${VERSION}
    image: "xwiki/cryptpad:${VERSION}"
    hostname: cryptpad

    labels:
      - traefik.enable=true
      - traefik.http.routers.cryptpad.rule=Host(pad)
      - traefik.http.services.cryptpad.loadbalancer.server.port=3000
      - "traefik.http.routers.cryptpad.tls=true"
      - "traefik.http.routers.cryptpad.entrypoints=web-secure"
      - "traefik.frontend.passHostHeader=true"
      - traefik.http.routers.cryptpad.middlewares=ssl-header
      - traefik.http.middlewares.ssl-header.headers.customrequestheaders.X-Forwarded-Proto=https

    environment:
      - USE_SSL=${USE_SSL}
      - STORAGE=${STORAGE}
      - LOG_TO_STDOUT=${LOG_TO_STDOUT}

    ports:
      - "3000:3000"
      - "3001:3001"

    restart: always
    volumes:
      - ./data/files:/cryptpad/datastore:rw
      - ./data/customize:/cryptpad/customize:rw
      - ./data/blob:/cryptpad/blob:rw
      - ./data/block:/cryptpad/block:rw
      - ./data/config:/cryptpad/cfg:rw
      - ./data/data:/cryptpad/data:rw
